# Generated by Django 5.2.6 on 2026-02-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainOrder",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="เลขที่เอกสาร"
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ชื่อร้านค้า/บริษัท",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Ordered", "Ordered"),
                            ("CorrectionNeeded", "CorrectionNeeded"),
                            ("SentToProcurement", "SentToProcurement"),
                            ("Closed", "Closed"),
                        ],
                        default="Draft",
                        max_length=30,
                    ),
                ),
                (
                    "total_estimated_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="ราคารวมประมาณการ",
                    ),
                ),
                (
                    "inspection_committee",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายชื่อกรรมการตรวจรับ"
                    ),
                ),
                (
                    "staff_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="บันทึกสิ่งที่ต้องแก้ไขจาก Staff"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "main_orders",
            },
        ),
        migrations.CreateModel(
            name="MasterItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_code", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=255)),
                ("standard_unit", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "master_items",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "project_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("project_name", models.CharField(max_length=255)),
                (
                    "budget_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="งบทั้งหมด",
                    ),
                ),
                (
                    "budget_reserved",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="งบที่ถูกจอง",
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="งบจ่ายจริง",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("User", "User"),
                            ("Staff", "Staff"),
                            ("Admin", "Admin"),
                        ],
                        default="User",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                ("vendor_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "vendors",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=255)),
                ("quantity_requested", models.IntegerField(default=1)),
                ("unit", models.CharField(max_length=50)),
                (
                    "estimated_unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Received", "Received"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.mainorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.AddField(
            model_name="mainorder",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.project",
            ),
        ),
        migrations.CreateModel(
            name="SubOrder",
            fields=[
                ("sub_order_id", models.AutoField(primary_key=True, serialize=False)),
                ("sub_order_no", models.CharField(max_length=50, unique=True)),
                ("received_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WaitingInspection", "WaitingInspection"),
                            ("Inspected", "Inspected"),
                            ("HandedOver", "HandedOver"),
                        ],
                        default="WaitingInspection",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "main_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_orders",
                        to="api.mainorder",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_orders_received",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "sub_orders",
            },
        ),
        migrations.CreateModel(
            name="InspectionDetail",
            fields=[
                ("inspection_id", models.AutoField(primary_key=True, serialize=False)),
                ("qty_received", models.IntegerField(default=0)),
                (
                    "actual_unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_actual_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("qr_code", models.CharField(blank=True, max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="api.orderitem",
                    ),
                ),
                (
                    "sub_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_details",
                        to="api.suborder",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_details",
            },
        ),
        migrations.AddField(
            model_name="mainorder",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_approved",
                to="api.user",
                verbose_name="ผู้อนุมัติ",
            ),
        ),
        migrations.AddField(
            model_name="mainorder",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_requested",
                to="api.user",
                verbose_name="ผู้สั่ง",
            ),
        ),
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="api.project",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to="api.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "project_assignments",
                "unique_together": {("project", "user")},
            },
        ),
    ]
