# Generated by Django 5.2.6 on 2026-02-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=255)),
                ("standard_unit", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "master_items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=50, unique=True)),
                ("order_title", models.CharField(max_length=255)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("พัสดุ", "พัสดุ"), ("ครุภัณฑ์", "ครุภัณฑ์")],
                        default="พัสดุ",
                        max_length=50,
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "ร่าง"),
                            ("รอ", "รอหัวหน้าอนุมัติ"),
                            ("รอรับของ", "รอรับของ"),
                            ("รับบางส่วน", "รับบางส่วน"),
                            ("รับครบ", "รับครบแล้ว"),
                            ("Rejected", "ไม่อนุมัติ"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                (
                    "total_estimated_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("required_date", models.DateField(blank=True, null=True)),
                ("order_description", models.TextField(blank=True, default="")),
                ("staff_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=50, unique=True)),
                ("project_name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[("พัสดุ", "พัสดุ"), ("ครุภัณฑ์", "ครุภัณฑ์")],
                        default="พัสดุ",
                        max_length=50,
                    ),
                ),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budget_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("status", models.CharField(default="Active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uid",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "ผู้ขอซื้อ"),
                            ("staff", "พัสดุ"),
                            ("boss", "หัวหน้าภาควิชา"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vendors",
            },
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="api.order",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_records",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="orders/%Y/%m/")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("unit", models.CharField(max_length=50)),
                (
                    "estimated_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("quantity_received", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_received", models.IntegerField(default=0)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.deliveryrecord",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.orderitem"
                    ),
                ),
            ],
            options={
                "db_table": "delivery_items",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.project",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="requester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.user",
            ),
        ),
    ]
