# Generated by Django 5.2.6 on 2025-09-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
