# Generated by Django 5.2.6 on 2026-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="ลิงก์สินค้า"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
        ),
    ]
