# Generated by Django 5.2.11 on 2026-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_admin_and_allauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ปฏิเสธ/แก้ไข'),
        ),
    ]
