# Generated by Django 5.2.6 on 2026-02-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_orderitem_product_link_orderitem_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
