# Generated by Django 5.2.11 on 2026-02-13 17:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchaseorder_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_equipment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ค่าครุภัณฑ์'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_materials',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ค่าวัสดุ'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_operations',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ค่าใช้สอย'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_remuneration',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ค่าตอบแทน'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้รับผิดชอบโครงการ'),
        ),
        migrations.AddField(
            model_name='project',
            name='ubufmis_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส UBUFMIS'),
        ),
    ]
