# Generated by Django 5.2.6 on 2026-02-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_orderedithistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderEditHistory",
        ),
    ]
