# Generated by Django 5.2.6 on 2026-02-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_orderedithistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEditHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "สร้างใหม่"),
                            ("update", "แก้ไข"),
                            ("status_change", "เปลี่ยนสถานะ"),
                            ("delete", "ลบ"),
                        ],
                        max_length=50,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "before_data",
                    models.JSONField(blank=True, null=True, verbose_name="ข้อมูลก่อนแก้ไข"),
                ),
                (
                    "after_data",
                    models.JSONField(blank=True, null=True, verbose_name="ข้อมูลหลังแก้ไข"),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ฟิลด์ที่เปลี่ยนแปลง"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_changes",
                        to="api.user",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="api.mainorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_edit_history",
                "ordering": ["-changed_at"],
            },
        ),
    ]
