# Generated by Django 5.2.6 on 2026-02-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_orderedithistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainorder",
            name="order_description",
            field=models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
        ),
        migrations.AddField(
            model_name="mainorder",
            name="order_title",
            field=models.CharField(default="", max_length=255, verbose_name="เรื่อง"),
        ),
        migrations.AddField(
            model_name="mainorder",
            name="required_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่ต้องการใช้งาน"
            ),
        ),
    ]
