# Generated by Django 5.2.6 on 2026-02-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_mainorder_order_description_mainorder_order_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_compensation",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="ค่าตอบแทน"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_equipment",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="ค่าครุภัณฑ์"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_materials",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="ค่าวัสดุ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_usage",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="ค่าใช้สอย"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="responsible_person",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ผู้รับผิดชอบโครงการ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ubufmis_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="รหัส UBUFMIS"
            ),
        ),
    ]
