# Generated by Django 5.2.6 on 2026-02-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_project_budget_compensation_project_budget_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suborder",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_orders_received",
                to="api.user",
            ),
        ),
    ]
