# Generated by Django 5.2.6 on 2026-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_suborder_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainorder",
            name="order_no",
            field=models.CharField(max_length=50, verbose_name="เลขที่เอกสาร"),
        ),
        migrations.AlterUniqueTogether(
            name="mainorder",
            unique_together={("project", "order_no")},
        ),
    ]
