# Generated by Django 5.2.6 on 2026-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_mainorder_order_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainorder",
            name="correction_count",
            field=models.IntegerField(default=0, verbose_name="จำนวนครั้งที่ส่งแก้ไข"),
        ),
    ]
